spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmdb?charset=utf8&serverTimezone=GMT&useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath*: /mapper/**/*.xml
  type-aliases-package: com.test.apigateway.dto
pagehelper:
  offset-as-page-num: true  #对使用 RowBounds 作为分页参数时有效,=true 会将 RowBounds 中的 offset 参数当成 pageNum 使用，可以用页码和页面大小两个参数进行分页
  reasonable: true   # 用户输入页数不在正常范围内，为了正常响应得到正确的结果页面
  page-size-zero: true  # 当pageSize=0或者RowBounds.limit=0时 查询全部结果
  support-methods-arguments: true
# 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，
# 自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页


