
server:
  port: 2000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: hello-service


