package com.test.apigateway.dto;

import java.io.Serializable;
import java.util.Date;

public class Button implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column button.id
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column button.button_name
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    private String buttonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column button.create_time
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column button.update_time
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column button.id
     *
     * @return the value of button.id
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public Button withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column button.id
     *
     * @param id the value for button.id
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column button.button_name
     *
     * @return the value of button.button_name
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public String getButtonName() {
        return buttonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public Button withButtonName(String buttonName) {
        this.setButtonName(buttonName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column button.button_name
     *
     * @param buttonName the value for button.button_name
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public void setButtonName(String buttonName) {
        this.buttonName = buttonName == null ? null : buttonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column button.create_time
     *
     * @return the value of button.create_time
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public Button withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column button.create_time
     *
     * @param createTime the value for button.create_time
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column button.update_time
     *
     * @return the value of button.update_time
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public Button withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column button.update_time
     *
     * @param updateTime the value for button.update_time
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", buttonName=").append(buttonName);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}