package com.test.apigateway.dto;

import java.io.Serializable;

public class MenuButton implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_button.id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_button.menu_id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_button.button_id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    private Integer buttonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_button.id
     *
     * @return the value of menu_button.id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public MenuButton withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_button.id
     *
     * @param id the value for menu_button.id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_button.menu_id
     *
     * @return the value of menu_button.menu_id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public MenuButton withMenuId(Integer menuId) {
        this.setMenuId(menuId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_button.menu_id
     *
     * @param menuId the value for menu_button.menu_id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_button.button_id
     *
     * @return the value of menu_button.button_id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public Integer getButtonId() {
        return buttonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public MenuButton withButtonId(Integer buttonId) {
        this.setButtonId(buttonId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_button.button_id
     *
     * @param buttonId the value for menu_button.button_id
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    public void setButtonId(Integer buttonId) {
        this.buttonId = buttonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", menuId=").append(menuId);
        sb.append(", buttonId=").append(buttonId);
        sb.append("]");
        return sb.toString();
    }
}