package com.test.apigateway.mapper;

import com.test.apigateway.dto.Button;
import com.test.apigateway.dto.ButtonExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface ButtonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    long countByExample(ButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    int deleteByExample(ButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    @Delete({
        "delete from button",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    @Insert({
        "insert into button (button_name, create_time, ",
        "update_time)",
        "values (#{buttonName,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Button record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    int insertSelective(Button record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    List<Button> selectByExampleWithRowbounds(ButtonExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    List<Button> selectByExample(ButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    @Select({
        "select",
        "id, button_name, create_time, update_time",
        "from button",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.test.apigateway.mapper.ButtonMapper.BaseResultMap")
    Button selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") Button record, @Param("example") ButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    int updateByExample(@Param("record") Button record, @Param("example") ButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    int updateByPrimaryKeySelective(Button record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table button
     *
     * @mbg.generated Thu Nov 07 18:11:12 CST 2019
     */
    @Update({
        "update button",
        "set button_name = #{buttonName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Button record);
}