package com.test.apigateway.mapper;

import com.test.apigateway.dto.MenuButton;
import com.test.apigateway.dto.MenuButtonExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface MenuButtonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    long countByExample(MenuButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    int deleteByExample(MenuButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    @Delete({
        "delete from menu_button",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    @Insert({
        "insert into menu_button (menu_id, button_id)",
        "values (#{menuId,jdbcType=INTEGER}, #{buttonId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(MenuButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    int insertSelective(MenuButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    List<MenuButton> selectByExampleWithRowbounds(MenuButtonExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    List<MenuButton> selectByExample(MenuButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    @Select({
        "select",
        "id, menu_id, button_id",
        "from menu_button",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.test.apigateway.mapper.MenuButtonMapper.BaseResultMap")
    MenuButton selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") MenuButton record, @Param("example") MenuButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    int updateByExample(@Param("record") MenuButton record, @Param("example") MenuButtonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    int updateByPrimaryKeySelective(MenuButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_button
     *
     * @mbg.generated Thu Nov 07 18:11:25 CST 2019
     */
    @Update({
        "update menu_button",
        "set menu_id = #{menuId,jdbcType=INTEGER},",
          "button_id = #{buttonId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MenuButton record);
}