package com.test.apigateway.mapper;

import com.test.apigateway.dto.RoleMenu;
import com.test.apigateway.dto.RoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    long countByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    int deleteByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    @Delete({
        "delete from role_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    @Insert({
        "insert into role_menu (menu_id, role_id, ",
        "order_num)",
        "values (#{menuId,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER}, ",
        "#{orderNum,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    List<RoleMenu> selectByExampleWithRowbounds(RoleMenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    List<RoleMenu> selectByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    @Select({
        "select",
        "id, menu_id, role_id, order_num",
        "from role_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.test.apigateway.mapper.RoleMenuMapper.BaseResultMap")
    RoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    int updateByExample(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    int updateByPrimaryKeySelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Thu Nov 07 18:10:52 CST 2019
     */
    @Update({
        "update role_menu",
        "set menu_id = #{menuId,jdbcType=INTEGER},",
          "role_id = #{roleId,jdbcType=INTEGER},",
          "order_num = #{orderNum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RoleMenu record);
}